# Generated by Django 5.0.14 on 2026-03-05 03:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('year_group', models.CharField(max_length=10)),
                ('academic_year', models.CharField(help_text="e.g., '2025-2026'", max_length=9)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cohorts',
                'ordering': ['-academic_year', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'enrollments',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_id', models.CharField(max_length=50, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('year_group', models.CharField(help_text="e.g., '7', '11'", max_length=10)),
                ('age_band', models.CharField(help_text="e.g., '11-12'", max_length=10)),
                ('eal', models.BooleanField(default=False, verbose_name='English as Additional Language')),
                ('first_language', models.CharField(blank=True, max_length=50)),
                ('accommodations', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'students',
                'ordering': ['student_id'],
            },
        ),
    ]
