# Generated by Django 5.0.14 on 2026-03-05 03:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='cohorts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.cohort'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student'),
        ),
        migrations.AddField(
            model_name='cohort',
            name='students',
            field=models.ManyToManyField(related_name='cohorts', through='students.Enrollment', to='students.student'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['year_group'], name='students_year_gr_0b186e_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['age_band'], name='students_age_ban_8b7ff3_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['student_id'], name='students_student_1ff8ed_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['student', 'cohort'], name='enrollments_student_e99cd9_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['cohort', 'enrolled_at'], name='enrollments_cohort__29f1dc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'cohort')},
        ),
        migrations.AddIndex(
            model_name='cohort',
            index=models.Index(fields=['teacher'], name='cohorts_teacher_21f937_idx'),
        ),
        migrations.AddIndex(
            model_name='cohort',
            index=models.Index(fields=['academic_year'], name='cohorts_academi_e399f9_idx'),
        ),
        migrations.AddIndex(
            model_name='cohort',
            index=models.Index(fields=['year_group'], name='cohorts_year_gr_cfd06f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cohort',
            unique_together={('name', 'teacher', 'academic_year')},
        ),
    ]
