# Generated by Django 5.0.14 on 2026-03-05 03:18

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceCandidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate_id', models.CharField(help_text="e.g., 'clip_0', 'clip_1'", max_length=20)),
                ('start_time', models.FloatField(help_text='Start time in seconds', validators=[django.core.validators.MinValueValidator(0)])),
                ('end_time', models.FloatField(help_text='End time in seconds', validators=[django.core.validators.MinValueValidator(0)])),
                ('type', models.CharField(choices=[('transcript_boundary', 'Transcript Boundary'), ('reason_dense', 'Reason Dense'), ('filler_heavy', 'Filler Heavy'), ('volume_variance', 'Volume Variance'), ('prompt_relevant', 'Prompt Relevant'), ('introduction', 'Introduction'), ('conclusion', 'Conclusion'), ('example_given', 'Example Given'), ('counterpoint', 'Counterpoint'), ('audience_reference', 'Audience Reference')], max_length=30)),
                ('summary', models.TextField(help_text='Brief description of the segment')),
                ('transcript_text', models.TextField(help_text='The transcript text for this segment')),
                ('features', models.JSONField(default=dict, help_text='Relevant features: {wpm, filler_count, reason_markers, etc.}')),
                ('relevant_strands', models.JSONField(default=list, help_text="List of strands this candidate is relevant for: ['physical', 'linguistic', 'cognitive', 'social_emotional']")),
            ],
            options={
                'db_table': 'evidence_candidates',
            },
        ),
        migrations.CreateModel(
            name='FeatureSignals',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quality_flag', models.CharField(choices=[('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='good', help_text='Overall media quality assessment', max_length=10)),
                ('wpm', models.FloatField(blank=True, help_text='Words per minute', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)])),
                ('pause_ratio', models.FloatField(blank=True, help_text='Ratio of pause time to total time', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('pause_count', models.IntegerField(blank=True, help_text='Number of pauses detected', null=True)),
                ('filler_frequency', models.FloatField(blank=True, help_text='Filler words per minute (um, uh, etc.)', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('filler_count', models.IntegerField(blank=True, null=True)),
                ('volume_variance', models.FloatField(blank=True, help_text='RMS energy variance (volume variability)', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('volume_mean', models.FloatField(blank=True, help_text='Mean volume level', null=True)),
                ('rhythm_stability', models.FloatField(blank=True, help_text='Rhythm consistency score', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('speech_rate_variance', models.FloatField(blank=True, help_text='Variance in speaking rate', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('sentence_count', models.IntegerField(blank=True, null=True)),
                ('sentence_length_mean', models.FloatField(blank=True, help_text='Average words per sentence', null=True)),
                ('sentence_length_variance', models.FloatField(blank=True, help_text='Variance in sentence length', null=True)),
                ('vocabulary_diversity', models.FloatField(blank=True, help_text='Type-token ratio or similar diversity measure', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('unique_word_count', models.IntegerField(blank=True, null=True)),
                ('prompt_relevance', models.FloatField(blank=True, help_text='Semantic relevance to prompt', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('clarity_score', models.FloatField(blank=True, help_text='Overall clarity based on audio + linguistic features', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('register_formality', models.FloatField(blank=True, help_text='Formality level of language', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('reason_marker_count', models.IntegerField(blank=True, null=True)),
                ('reason_density', models.FloatField(blank=True, help_text='Reason markers per 100 words (because, for example, etc.)', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('has_introduction', models.BooleanField(blank=True, null=True)),
                ('has_conclusion', models.BooleanField(blank=True, null=True)),
                ('structure_completeness', models.FloatField(blank=True, help_text='How complete the structure (intro/body/conclusion)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('counterpoint_count', models.IntegerField(blank=True, null=True)),
                ('counterpoint_density', models.FloatField(blank=True, help_text='Counterpoint markers per 100 words (however, although, etc.)', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('logical_connector_count', models.IntegerField(blank=True, null=True)),
                ('logical_connector_density', models.FloatField(blank=True, help_text='Logical connectors per 100 words (therefore, thus, etc.)', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('evidence_marker_count', models.IntegerField(blank=True, null=True)),
                ('evidence_density', models.FloatField(blank=True, help_text='Evidence markers per 100 words', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('coherence_score', models.FloatField(blank=True, help_text='Discourse coherence score', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('audience_reference_count', models.IntegerField(blank=True, null=True)),
                ('audience_reference_frequency', models.FloatField(blank=True, help_text='Audience references per 100 words', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('intention_clarity', models.FloatField(blank=True, help_text='Clarity of communicative intent', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('sentiment_positive', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('sentiment_negative', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('sentiment_neutral', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('sentiment_compound', models.FloatField(blank=True, help_text='Overall sentiment compound score', null=True, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(1)])),
                ('confidence_score', models.FloatField(blank=True, help_text='Speaker confidence estimate', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('extracted_at', models.DateTimeField(auto_now_add=True)),
                ('extraction_duration_seconds', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'feature_signals',
            },
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('segments', models.JSONField(help_text='Transcript segments with word-level timestamps')),
                ('full_text', models.TextField(help_text='Complete transcript text')),
                ('language', models.CharField(default='en-GB', max_length=10)),
                ('confidence', models.FloatField(blank=True, help_text='Overall transcription confidence', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('provider', models.CharField(help_text='STT provider: openai, aws, etc.', max_length=50)),
                ('model_version', models.CharField(help_text='Model version used', max_length=50)),
                ('processing_time_seconds', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'transcripts',
            },
        ),
    ]
