# Generated by Django 5.0.14 on 2026-03-05 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0001_initial'),
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencecandidate',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_candidates', to='assessments.assessment'),
        ),
        migrations.AddField(
            model_name='featuresignals',
            name='assessment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feature_signals', to='assessments.assessment'),
        ),
        migrations.AddField(
            model_name='transcript',
            name='assessment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcript', to='assessments.assessment'),
        ),
        migrations.AddIndex(
            model_name='evidencecandidate',
            index=models.Index(fields=['assessment'], name='evidence_ca_assessm_4ba359_idx'),
        ),
        migrations.AddIndex(
            model_name='evidencecandidate',
            index=models.Index(fields=['assessment', 'type'], name='evidence_ca_assessm_28a933_idx'),
        ),
        migrations.AddIndex(
            model_name='evidencecandidate',
            index=models.Index(fields=['type'], name='evidence_ca_type_fcd9df_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='evidencecandidate',
            unique_together={('assessment', 'candidate_id')},
        ),
        migrations.AddIndex(
            model_name='featuresignals',
            index=models.Index(fields=['assessment'], name='feature_sig_assessm_c7065c_idx'),
        ),
        migrations.AddIndex(
            model_name='featuresignals',
            index=models.Index(fields=['quality_flag'], name='feature_sig_quality_8338f4_idx'),
        ),
        migrations.AddIndex(
            model_name='transcript',
            index=models.Index(fields=['assessment'], name='transcripts_assessm_8df3b2_idx'),
        ),
        migrations.AddIndex(
            model_name='transcript',
            index=models.Index(fields=['full_text'], name='transcripts_full_text_fts'),
        ),
    ]
