# Generated by Django 5.0.14 on 2026-03-05 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('score_changed', 'Score Changed'), ('clip_changed', 'Evidence Clip Changed'), ('feedback_edited', 'Feedback Edited'), ('signed_off', 'Report Signed Off'), ('assessment_created', 'Assessment Created'), ('assessment_uploaded', 'Recording Uploaded'), ('processing_started', 'Processing Started'), ('draft_generated', 'Draft Report Generated'), ('notes_added', 'Teacher Notes Added'), ('consent_updated', 'Consent Updated'), ('student_created', 'Student Created'), ('student_updated', 'Student Updated'), ('user_login', 'User Login'), ('user_logout', 'User Logout'), ('export_generated', 'Export Generated')], max_length=30)),
                ('object_type', models.CharField(help_text="Model name: 'Assessment', 'DraftReport', etc.", max_length=50)),
                ('object_id', models.CharField(help_text='UUID or ID of the affected object', max_length=50)),
                ('field', models.CharField(blank=True, help_text='Field name that was modified', max_length=50)),
                ('old_value', models.JSONField(blank=True, help_text='Previous value (for updates)', null=True)),
                ('new_value', models.JSONField(blank=True, help_text='New value after change', null=True)),
                ('description', models.TextField(blank=True, help_text='Human-readable description of the action')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context: IP address, user agent, etc.')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ReportChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('strand_band', 'Strand Band Changed'), ('evidence_clip', 'Evidence Clip Changed'), ('justification', 'Justification Edited'), ('strength', 'Strength Modified'), ('next_step', 'Next Step Modified'), ('goal', 'Goal Modified'), ('teacher_notes', 'Teacher Notes Added/Edited')], max_length=20)),
                ('strand', models.CharField(blank=True, help_text='Which strand was affected (if applicable)', max_length=20)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('change_reason', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'report_change_history',
                'ordering': ['-changed_at'],
            },
        ),
    ]
