# Generated by Django 5.0.14 on 2026-03-05 03:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit', '0001_initial'),
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportchangehistory',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportchangehistory',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_history', to='reports.draftreport'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user'], name='audit_logs_user_id_73c422_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['object_type', 'object_id'], name='audit_logs_object__457405_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action'], name='audit_logs_action_31f574_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['timestamp'], name='audit_logs_timesta_423be6_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['object_type', 'object_id', 'timestamp'], name='audit_logs_object__0e8d3c_idx'),
        ),
        migrations.AddIndex(
            model_name='reportchangehistory',
            index=models.Index(fields=['report'], name='report_chan_report__216a10_idx'),
        ),
        migrations.AddIndex(
            model_name='reportchangehistory',
            index=models.Index(fields=['changed_by'], name='report_chan_changed_548be9_idx'),
        ),
        migrations.AddIndex(
            model_name='reportchangehistory',
            index=models.Index(fields=['changed_at'], name='report_chan_changed_b2c1fb_idx'),
        ),
        migrations.AddIndex(
            model_name='reportchangehistory',
            index=models.Index(fields=['report', 'changed_at'], name='report_chan_report__0a7fba_idx'),
        ),
    ]
