# Generated by Django 5.0.14 on 2026-03-05 03:18

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mode', models.CharField(choices=[('presenting', 'Presenting'), ('explaining', 'Explaining'), ('persuading', 'Persuading')], help_text='Mode of talk: presenting, explaining, or persuading', max_length=20)),
                ('prompt', models.TextField(help_text='The prompt or topic given to the student')),
                ('time_limit_seconds', models.IntegerField(default=180, help_text='Time limit in seconds (30s to 10min)', validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(600)])),
                ('consent_obtained', models.BooleanField(default=False)),
                ('consent_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('uploading', 'Uploading'), ('processing', 'Processing'), ('draft_ready', 'Draft Ready'), ('under_review', 'Under Review'), ('signed_off', 'Signed Off'), ('error', 'Error')], default='pending', max_length=20)),
                ('status_message', models.TextField(blank=True, help_text='Human-readable status or error message')),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'assessments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('file_size_bytes', models.BigIntegerField()),
                ('s3_bucket', models.CharField(max_length=100)),
                ('s3_key', models.CharField(max_length=500)),
                ('audio_extracted', models.BooleanField(default=False)),
                ('audio_s3_key', models.CharField(blank=True, max_length=500)),
                ('duration_seconds', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('video_quality_score', models.FloatField(blank=True, help_text='Video quality score 0-1', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('audio_quality_score', models.FloatField(blank=True, help_text='Audio quality score 0-1', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('video_codec', models.CharField(blank=True, max_length=50)),
                ('audio_codec', models.CharField(blank=True, max_length=50)),
                ('resolution', models.CharField(blank=True, help_text="e.g., '1920x1080'", max_length=20)),
                ('frame_rate', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'recordings',
            },
        ),
    ]
