# Generated by Django 5.0.14 on 2026-03-05 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='students.cohort'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='students.student'),
        ),
        migrations.AddField(
            model_name='recording',
            name='assessment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recording', to='assessments.assessment'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['student'], name='assessments_student_5c50a4_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['cohort'], name='assessments_cohort__cf68a5_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['status'], name='assessments_status_621393_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['created_at'], name='assessments_created_8a51b9_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['mode'], name='assessments_mode_8ebd84_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['cohort', 'status', 'created_at'], name='assessments_cohort__78f6a6_idx'),
        ),
        migrations.AddIndex(
            model_name='recording',
            index=models.Index(fields=['assessment'], name='recordings_assessm_fafe9a_idx'),
        ),
    ]
