# Generated by Django 5.0.14 on 2026-03-05 03:18

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignedReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('physical_score', models.JSONField(default=dict, help_text='Final physical strand score after teacher review')),
                ('linguistic_score', models.JSONField(default=dict, help_text='Final linguistic strand score after teacher review')),
                ('cognitive_score', models.JSONField(default=dict, help_text='Final cognitive strand score after teacher review')),
                ('social_emotional_score', models.JSONField(default=dict, help_text='Final social-emotional strand score after teacher review')),
                ('feedback', models.JSONField(default=dict, help_text='Final feedback after teacher edits')),
                ('teacher_notes', models.TextField(blank=True, help_text='Private notes for teacher reference')),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('signature_hash', models.CharField(blank=True, help_text='Hash of report content for verification', max_length=64)),
                ('changes_summary', models.JSONField(blank=True, default=dict, help_text='\n        {\n            "scores_modified": ["physical", "cognitive"],\n            "clips_swapped": {"physical": ["clip_0", "clip_2"]},\n            "feedback_edited": true,\n            "notes_added": true\n        }\n        ')),
                ('exported_at', models.DateTimeField(blank=True, null=True)),
                ('export_format', models.CharField(blank=True, choices=[('pdf', 'PDF'), ('csv', 'CSV'), ('json', 'JSON')], max_length=20)),
            ],
            options={
                'db_table': 'signed_reports',
            },
        ),
        migrations.CreateModel(
            name='DraftReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('physical_score', models.JSONField(default=dict, help_text='\n        {\n            "band": "emerging|expected|exceeding",\n            "confidence": 0.0-1.0,\n            "evidence_clips": ["clip_0", "clip_3"],\n            "justification": "Rubric-based justification text",\n            "subskills": {\n                "voice_projection": {"score": 0.7, "evidence": ["clip_1"]},\n                "clarity": {"score": 0.8, "evidence": ["clip_2"]}\n            }\n        }\n        ')),
                ('linguistic_score', models.JSONField(default=dict, help_text='Same structure as physical_score')),
                ('cognitive_score', models.JSONField(default=dict, help_text='Same structure as physical_score')),
                ('social_emotional_score', models.JSONField(default=dict, help_text='Same structure as physical_score')),
                ('overall_confidence', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('feedback', models.JSONField(default=dict, help_text='\n        {\n            "strengths": [\n                {"text": "Strength 1", "strand": "cognitive", "evidence": "clip_0"},\n                {"text": "Strength 2", "strand": "physical", "evidence": "clip_3"},\n                {"text": "Strength 3", "strand": "linguistic", "evidence": "clip_5"}\n            ],\n            "next_steps": [\n                {"text": "Next step 1", "strand": "social_emotional", "specific": true},\n                {"text": "Next step 2", "strand": "cognitive", "specific": true},\n                {"text": "Next step 3", "strand": "physical", "specific": true}\n            ],\n            "goals": [\n                "Student-friendly practice goal 1",\n                "Student-friendly practice goal 2"\n            ]\n        }\n        ')),
                ('mode_specific_notes', models.TextField(blank=True, help_text='Mode-specific feedback notes')),
                ('eal_scaffolds', models.JSONField(blank=True, default=dict, help_text='\n        {\n            "separated_scores": {\n                "reasoning": "emerging|expected|exceeding",\n                "language_surface": "emerging|expected|exceeding"\n            },\n            "scaffolds": [\n                "Sentence stem suggestion 1",\n                "Planning frame suggestion"\n            ]\n        }\n        ')),
                ('ai_model', models.CharField(help_text='LLM model used for scoring', max_length=100)),
                ('ai_provider', models.CharField(help_text='Provider: openai, anthropic, etc.', max_length=50)),
                ('ai_version', models.CharField(help_text='Model version', max_length=50)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generation_duration_seconds', models.FloatField(blank=True, null=True)),
                ('benchmark_version', models.CharField(help_text='Version of benchmark definitions used', max_length=20)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('warnings', models.JSONField(default=list, help_text="List of warnings: ['low_audio_quality', 'insufficient_evidence', etc.]")),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='draft_report', to='assessments.assessment')),
            ],
            options={
                'db_table': 'draft_reports',
            },
        ),
    ]
