# Generated by Django 5.0.14 on 2026-03-05 03:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0002_initial'),
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='draftreport',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_draft_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='signedreport',
            name='assessment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signed_report', to='assessments.assessment'),
        ),
        migrations.AddField(
            model_name='signedreport',
            name='draft_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_version', to='reports.draftreport'),
        ),
        migrations.AddField(
            model_name='signedreport',
            name='signed_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['teacher', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='draftreport',
            index=models.Index(fields=['assessment'], name='draft_repor_assessm_68bca6_idx'),
        ),
        migrations.AddIndex(
            model_name='draftreport',
            index=models.Index(fields=['generated_at'], name='draft_repor_generat_65a83c_idx'),
        ),
        migrations.AddIndex(
            model_name='draftreport',
            index=models.Index(fields=['is_reviewed'], name='draft_repor_is_revi_3428aa_idx'),
        ),
        migrations.AddIndex(
            model_name='draftreport',
            index=models.Index(fields=['reviewed_by'], name='draft_repor_reviewe_94471a_idx'),
        ),
        migrations.AddIndex(
            model_name='signedreport',
            index=models.Index(fields=['assessment'], name='signed_repo_assessm_c9bcc0_idx'),
        ),
        migrations.AddIndex(
            model_name='signedreport',
            index=models.Index(fields=['signed_by'], name='signed_repo_signed__ce0737_idx'),
        ),
        migrations.AddIndex(
            model_name='signedreport',
            index=models.Index(fields=['signed_at'], name='signed_repo_signed__732e69_idx'),
        ),
        migrations.AddIndex(
            model_name='signedreport',
            index=models.Index(fields=['created_at'], name='signed_repo_created_c263d2_idx'),
        ),
    ]
